### ISSUE TITLE
Fixed signal sampling rate

### ISSUE THREAD

**Issue by ansariyusuf** [klean2050/ecg-augmentations#1]
Hi,

Thank you for initiating this repo. It is much needed in the PyTorch space. I was playing with the mask transforms and noticed that you had fixed the sampling of the ECG signals. However, this has to be an argument from the user depending on the ECG signal he/she is working with. 

Am I missing something? Kindly clarify at the earliest.

Yusuf

**Comment by klean2050** [comment]
Thank you Yusuf,

You are correct, I am gonna push a set of new changes over the next week, among them the sampling rate argument.

**Comment by ansariyusuf** [comment]
Sounds great! Let me know when you push the new set of changes so that I can reflect it in my workspace.

**Comment by klean2050** [comment]
Just pushed a set of changes, hope yours is fixed. You are also welcome ro contribute with pull requests.

**Comment by ansariyusuf** [comment]
Thank you, I will keep in mind to make a pull request and push add new features.
