### ISSUE TITLE
Mask Augmentation for 12 lead ECG

### ISSUE THREAD

**Issue by ansariyusuf** [klean2050/ecg-augmentations#2]
Hi,

Thank you for accommodating my request for the sampling rate. I have been testing the Mask augmentations. They seem to work well for a single lead ECG. However, they don't support 12-lead ECG. This is crucial because I cannot individually augment every lead differently because it will distort the information sequence. Do you think it will be feasible to add support for multi-lead ECG data? other transforms invert, reverse work with 12-lead ECG data.

**Comment by klean2050** [comment]
Hi,

Thank you for your comment. The last commit updated all functions to work with ECG of multiple leads. Enjoy :) and drop your comments on possible bugs.
